export const directory = {
  name: "root",
  toggled: true,
  children: [
    {
      id: 1,
      nombre: "a",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 63,
      type: "adult",
      path: [0],
      extension: "folder",
    },
    {
      id: 2,
      nombre: "b",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "adult",
      parentId: 1,
      path: [0, 0],
      extension: "txt",
    },
    {
      id: 3,
      nombre: "c",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "child",
      parentId: 1,
      path: [0, 1],
      extension: "folder",
    },
    {
      id: 4,
      nombre: "d",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      sex: "Female",
      type: "child",
      parentId: 3,
      path: [0, 1, 0],
      extension: "txt",
    },
    {
      id: 5,
      nombre: "e",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      sex: "Female",
      type: "child",
      path: [1],
      extension: "folder",
    },
    {
      id: 6,
      nombre: "P",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "adult",
      path: [1, 0],
      extension: "folder",
    },
    {
      id: 7,
      nombre: "G",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "adult",
      path: [1, 0],
      extension: "folder",
    },
    {
      id: 8,
      nombre: "f",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "child",
      parentId: 6,
      path: [1, 0],
      extension: "txt",
    },
    {
      id: 9,
      nombre: "f",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "child",
      parentId: 6,
      path: [1, 0],
      extension: "txt",
    },
    {
      id: 10,
      nombre: "f",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "child",
      parentId: 5,
      path: [1, 0],
      extension: "txt",
    },
    {
      id: 11,
      nombre: "d",
      fecha_modificacion: "Baran",
      modificado_por: 1987,
      tamaño: 34,
      type: "child",
      parentId: 7,
      path: [1, 0],
      extension: "undefined",
    },
  ],
};
